services:
  - name: redis-stack
    type: web
    env: docker
    repo: https://github.com/emgromero-odilo/test-redis-emgromero.git
    branch: main
    plan: free
    disk:
      name: redis-data
      mountPath: /data
      sizeGB: 1
    buildCommand: docker build -t redis-proxy .
    startCommand: docker run -p 6379:6379 redis-proxy
