services:
  - name: redis-stack
    type: web
    env: docker
    repo: https://github.com/emgromero-odilo/test-redis-emgromero.git
    branch: main
    plan: free
    disk:
      name: redis-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: REDIS_PORT
        value: "6379"
    dockerfilePath: ./Dockerfile # Asegúrate de que el Dockerfile esté en la raíz del repo
